runtime: python27
api_version: 1
threadsafe: true
skip_files:
- frontend
- \.git
- \.gitignore
- test_*
- ^(.*/)?.*\.map$
- ^(.*/)?.*\.pyc$

libraries:
- name: ssl
  version: latest

handlers:
- url: /admin
  script: main.app
  login: admin
  auth_fail_action: redirect
- url: /api/.*
  script: main.app
  login: admin
  auth_fail_action: redirect
- url: /cron/*
  script: main.app
  login: admin
  auth_fail_action: redirect

- url: /static
  static_dir: static
- url: /
  static_files: static/index.html
  upload: static/index.html
  login: admin
  auth_fail_action: redirect
# - url: /.*
#   script: main.app