runtime: python27
api_version: 1
threadsafe: true
skip_files:
- ^(.*/)?node_modules/(.*/)?
- ^(.*/)?.*\.ts$
- \.gitignore
- ^\.git/.*

libraries:
- name: ssl
  version: latest

handlers:
- url: /static
  static_dir: static
- url: /admin/*
  script: main.app
  login: admin
  auth_fail_action: redirect
- url: /host/*
  script: main.app
  login: admin
  auth_fail_action: redirect
- url: /cron/*
  script: main.app
  login: admin
  auth_fail_action: redirect
- url: /.*
  script: main.app