runtime: python27
api_version: 1
threadsafe: true
skip_files:
- \.git
- \.gitignore
- test_*
- ^(.*/)?.*\.map$
- ^(.*/)?.*\.pyc$

libraries:
- name: ssl
  version: latest

handlers:
- url: /admin
  script: main.app
  login: admin
  auth_fail_action: redirect
- url: /api/.*
  script: main.app
  login: admin
  auth_fail_action: redirect

- url: /frontend
  static_dir: frontend
# - url: /.*
#   script: main.app